package example

const (
	Unitialised   = "Unitialised"
	Initialised   = "Initialised"
	Available     = "Available"
	Preparing     = "Preparing"
	Charging      = "Charging"
	SuspendedEV   = "SuspendedEV"
	SuspendedEVSE = "SuspendedEVSE"
	Finishing     = "Finishing"
	Reserved      = "Reserved"
	Unavailable   = "Unavailable"
	Faulted       = "Faulted"
	Parking       = "Parking"
	Done          = "Done"
	Failed        = "Failed"

	Configure                = "Configure"
	HandleBootNotification   = "HandleBootNotification"
	HandleStatusNotification = "HandleStatusNotification"
	PlugInEV                 = "PlugInEV"
	RemoteStart              = "RemoteStart"
	HandleStart              = "HandleStart"
	HandleMeterValues        = "HandleMeterValues"
	SuspendEV                = "SuspendEV"
	SuspendEVSE              = "SuspendEVSE"
	Resume                   = "Resume"
	RemoteStop               = "RemoteStop"
	HandleStop               = "HandleStop"
	UnplugEV                 = "UnplugEV"
	Cordon                   = "Cordon"
	Shutdown                 = "Shutdown"
)
